# Intro

## Links
High level overview : https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html



## Prerequisites

It's assumed that your using the environment as defined by the provided yaml file.
    env_packages.yml

# Tensors Intro

- A matrix is a rank 2-tensor but a tensor is a much more general construct than a matrix.
    - NB A rank-2 tensor is basically a square array, which is just one of many possible tensors
    - NB Tensor can be much higher in dimensionality than a matrix.
- A tensor is a matrix whose basis can change.
- Physicist's define "A tensor is what transforms like a tensor"
- Mathematicians define a "tensor" to be a multilinear function: a function of several vector variables that is "linear in each variable separately". A "tensor field" is a "tensor-valued function".



## Pytorch v Numpy

Let's begin by looking at tensors vs numpy arrays

In [3]:
import torch
import numpy as np 

data = [[1, 2], [3, 4]]

x_data = torch.tensor(data)
x_np = torch.from_numpy(np.array(data))

# Pretty simpy right?
print(x_data)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [8]:
# much like numpy pytorch provides some easy to use constructors
print(torch.rand((2,3,)))
print(torch.ones((3,3,)))
print(torch.zeros((3,1,)))
# a lot more can be found here 
# https://pytorch.org/docs/stable/torch.html#tensor-creation-ops

tensor([[0.4768, 0.4614, 0.1822],
        [0.8042, 0.8949, 0.8578]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.],
        [0.],
        [0.]])


In [9]:
# Much like numpy they also have attributes
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [17]:
# there is also many operations that can be performed on a tensor
# https://pytorch.org/docs/stable/torch.html

# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

tensor = torch.ones(4, 4)
tensor[:,1] = 0
tensor[3,0]=3
tensor[3,3]=9
print('tensor',tensor)

# Joining tensors 
# You can use torch.cat to concatenate a sequence of tensors along a given dimension. 
# See also torch.stack, another tensor joining op that is subtly different from torch.cat

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print('torch.cat',t1)

# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

# This computes the matrix multiplication between two tensors
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
# print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

# Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x
print(tensor, "\n")
tensor.add_(5)
print(tensor)


Device tensor is stored on: cuda:0
tensor tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [3., 0., 1., 9.]])
torch.cat tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [3., 0., 1., 9., 3., 0., 1., 9., 3., 0., 1., 9.]])
tensor.mul(tensor) 
 tensor([[ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.],
        [ 9.,  0.,  1., 81.]]) 

tensor * tensor 
 tensor([[ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.],
        [ 9.,  0.,  1., 81.]])
tensor.matmul(tensor.T) 
 tensor([[ 3.,  3.,  3., 13.],
        [ 3.,  3.,  3., 13.],
        [ 3.,  3.,  3., 13.],
        [13., 13., 13., 91.]]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [3., 0., 1., 9.]]) 

tensor([[ 6.,  5.,  6.,  6.],
        [ 6.,  5.,  6.,  6.],
        [ 6

## Torch Autograd


From https://pytorch.org/docs/stable/autograd.html


torch.autograd provides classes and functions implementing automatic differentiation of arbitrary scalar valued functions. It requires minimal changes to the existing code - you only need to declare Tensor s for which gradients should be computed with the requires_grad=True keyword. As of now, we only support autograd for floating point Tensor types ( half, float, double and bfloat16) and complex Tensor types (cfloat, cdouble).
